In [1]:
from utils.hnsw_module import *
import pandas as pd
from utils.evaluation import * 
data = pd.read_csv('data/embeddings_films.csv', usecols=[i for i in range(2, 386)])
train_data = data[:20000]
test_data = data[20000:]

train_data = train_data.to_numpy()
test_data = test_data.to_numpy()

In [2]:
train_data = train_data.astype(np.float32)
test_data = test_data.astype(np.float32)

In [3]:
from utils.CustomFAISS import *

In [4]:
from utils.IVFPQ import CustomIVFPQ

In [5]:
# Step 2: Initialize the CustomIVFPQ class with appropriate parameters
d = train_data.shape[1]  # Dimension of the embeddings
nlist = 8  # Number of clusters
nprobe = 8   # Number of clusters to probe
m = 8        # Number of segments for PQ

ivfpq = CustomIVFPQ(d, nlist, nprobe, m, estimator='kmeans')

# Step 3: Train the index with the training data
print("Training the index...")
ivfpq.train(train_data)

# Step 4: Add the training data to the index
print("Adding data to the index...")
ivfpq.add(train_data)

Training the index...
Training data shape after PCA (if applied): (20000, 384)
Training PQ on cluster 0, segment 0, data shape: (2990, 48)
Training PQ on cluster 0, segment 1, data shape: (2990, 48)
Training PQ on cluster 0, segment 2, data shape: (2990, 48)
Training PQ on cluster 0, segment 3, data shape: (2990, 48)
Training PQ on cluster 0, segment 4, data shape: (2990, 48)
Training PQ on cluster 0, segment 5, data shape: (2990, 48)
Training PQ on cluster 0, segment 6, data shape: (2990, 48)
Training PQ on cluster 0, segment 7, data shape: (2990, 48)
Training PQ on cluster 1, segment 0, data shape: (4417, 48)
Training PQ on cluster 1, segment 1, data shape: (4417, 48)
Training PQ on cluster 1, segment 2, data shape: (4417, 48)
Training PQ on cluster 1, segment 3, data shape: (4417, 48)
Training PQ on cluster 1, segment 4, data shape: (4417, 48)
Training PQ on cluster 1, segment 5, data shape: (4417, 48)
Training PQ on cluster 1, segment 6, data shape: (4417, 48)
Training PQ on cluste

c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 2, segment 1, data shape: (1959, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 2, segment 2, data shape: (1959, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 2, segment 3, data shape: (1959, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 2, segment 4, data shape: (1959, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 2, segment 5, data shape: (1959, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 2, segment 6, data shape: (1959, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 2, segment 7, data shape: (1959, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=8.
  warnings.warn(


Training PQ on cluster 3, segment 0, data shape: (2938, 48)
Training PQ on cluster 3, segment 1, data shape: (2938, 48)
Training PQ on cluster 3, segment 2, data shape: (2938, 48)
Training PQ on cluster 3, segment 3, data shape: (2938, 48)
Training PQ on cluster 3, segment 4, data shape: (2938, 48)
Training PQ on cluster 3, segment 5, data shape: (2938, 48)
Training PQ on cluster 3, segment 6, data shape: (2938, 48)
Training PQ on cluster 3, segment 7, data shape: (2938, 48)
Training PQ on cluster 4, segment 0, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 4, segment 1, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 4, segment 2, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 4, segment 3, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 4, segment 4, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 4, segment 5, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 4, segment 6, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 4, segment 7, data shape: (2115, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 5, segment 0, data shape: (716, 48)
Training PQ on cluster 5, segment 1, data shape: (716, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(
c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


Training PQ on cluster 5, segment 2, data shape: (716, 48)
Training PQ on cluster 5, segment 3, data shape: (716, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(
c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


Training PQ on cluster 5, segment 4, data shape: (716, 48)
Training PQ on cluster 5, segment 5, data shape: (716, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(
c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


Training PQ on cluster 5, segment 6, data shape: (716, 48)
Training PQ on cluster 5, segment 7, data shape: (716, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(
c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


Training PQ on cluster 6, segment 0, data shape: (2595, 48)
Training PQ on cluster 6, segment 1, data shape: (2595, 48)
Training PQ on cluster 6, segment 2, data shape: (2595, 48)
Training PQ on cluster 6, segment 3, data shape: (2595, 48)
Training PQ on cluster 6, segment 4, data shape: (2595, 48)
Training PQ on cluster 6, segment 5, data shape: (2595, 48)
Training PQ on cluster 6, segment 6, data shape: (2595, 48)
Training PQ on cluster 6, segment 7, data shape: (2595, 48)
Training PQ on cluster 7, segment 0, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 7, segment 1, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 7, segment 2, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 7, segment 3, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 7, segment 4, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 7, segment 5, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 7, segment 6, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Training PQ on cluster 7, segment 7, data shape: (2270, 48)


c:\Users\billya\AppData\Local\miniconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1426: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=9.
  warnings.warn(


Adding data to the index...
Encoding cluster 0, data shape before encode: (2990, 384)
Encoding segment 0, data shape: (2990, 48)
Encoding segment 1, data shape: (2990, 48)
Encoding segment 2, data shape: (2990, 48)
Encoding segment 3, data shape: (2990, 48)
Encoding segment 4, data shape: (2990, 48)
Encoding segment 5, data shape: (2990, 48)
Encoding segment 6, data shape: (2990, 48)
Encoding segment 7, data shape: (2990, 48)
Encoding cluster 1, data shape before encode: (4417, 384)
Encoding segment 0, data shape: (4417, 48)
Encoding segment 1, data shape: (4417, 48)
Encoding segment 2, data shape: (4417, 48)
Encoding segment 3, data shape: (4417, 48)
Encoding segment 4, data shape: (4417, 48)
Encoding segment 5, data shape: (4417, 48)
Encoding segment 6, data shape: (4417, 48)
Encoding segment 7, data shape: (4417, 48)
Encoding cluster 2, data shape before encode: (1959, 384)
Encoding segment 0, data shape: (1959, 48)
Encoding segment 1, data shape: (1959, 48)
Encoding segment 2, data

In [6]:

# Step 5: Perform a search on some test data
k = 10  # Number of nearest neighbors to search for
Y = train_data[:10] # Take first 5 points from the test set for demonstration

distances, sorted_indices, distance_table, X = ivfpq.search(Y, k)


In [7]:
sorted_indices

[array([17948, 14771,   312,  9054, 10061, 14378,     0, 17997, 10461,
        19362]),
 array([14771, 11621,  4643,  1690, 10482, 19035, 10061,   312, 19362,
        10929]),
 array([    2,     5,     6,     3, 17948, 17943,     4,     8,  4643,
         4644]),
 array([    3,     2, 17948,     5,    12, 17943,  4643, 18855,     6,
        11250]),
 array([    4,     5,     2,     6, 17948, 17943,     8, 18299,    75,
        19636]),
 array([    2,     5,     6,     3, 17948, 17943,     4,  4643,  3577,
         6587]),
 array([    2,     5,     6, 17943,     4,     3, 13901, 17948,     8,
        15186]),
 array([    7, 14378, 17997,  4720, 10061,     8,  4516, 17948, 13977,
        13480]),
 array([    8, 17997, 15300, 17948, 15267, 18016, 17943, 13265, 13542,
            9]),
 array([    9,     2, 17948, 17997, 14294, 13542, 10061, 15461,     3,
            5])]

In [8]:
np.argsort(distance_table.flatten())[:10]

array([7230, 6117, 7328, 6132, 6567, 7989, 4836, 5189, 7176, 6743],
      dtype=int64)

In [8]:
import faiss 

index = faiss.IndexFlatL2(train_data.shape[1])
index.train(train_data)
index.add(train_data)

In [9]:
dist, indices = index.search(train_data[:10], k = 10)

In [32]:
indices

array([[    0,    10,    15, 18031,    21,     1,    19, 18032,    13,
            7],
       [    1, 18031,    15,     0,    10,    14, 18032,    13,    19,
           21],
       [    2,     6,     3,     5,     9,     4,     8,  9814,  5677,
        17955],
       [    3,     2,     5,     6,     9,     4,     8, 12366,  1681,
         5865],
       [    4,     2,     5,     6,     3, 18558,     9,  9814,  6949,
        19622],
       [    5,     6,     2,     3,     4, 19602, 12557,  8080, 11541,
        14570],
       [    6,     5,     2,     3,     4, 12948,  8335, 17077, 11313,
         2601],
       [    7,    21,     0,     8,    15, 18031,    10,    22,    13,
        18032],
       [    8,    21,     9,     7,  5677,     0,    17,    20,  5679,
           10],
       [    9,     8,     2,     3, 17939,  5677, 17941, 17944, 17955,
         9814]], dtype=int64)

In [33]:
from utils.evaluation import * 
from utils.hnsw_module import *


In [13]:
from tqdm import tqdm

hnsw = HNSW('euclidean', m=4, ef=20)

In [14]:
evaluate = KNNEvaluation(train_data, test_data,hnsw, k=10, ef=200, metric='euclidean')

In [15]:
%%timeit

evaluate.brute_force_knn(train_data, test_data[100:101], k = 10, metric = "euclidean")

21.8 ms ± 457 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
def evaluate_recall(indices_brute,indices_hnsw):
    recall_at_1 = 0
    recall_at_10 = 0
    smetric = 0

    for i in range(len(indices_brute)):

        # Evaluate recall@1
        if indices_brute[i][0] == indices_hnsw[i][0]:
            recall_at_1 += 1

        # Evaluate recall@10
    
        for t in range(10):
            for y in range(10):
                if indices_hnsw[i][t] == indices_brute[i][y]:
                    recall_at_10 += 1 

    
        for t in range(9):
            for y in range(9):
                if indices_hnsw[i][t] == indices_brute[i][y]:
                    smetric += 9 - y
    
    smetric /= len(indices_brute)
    recall_at_1 /= len(indices_brute)
    recall_at_10 /= len(indices_brute)  * 10 

    return recall_at_1, recall_at_10, smetric

In [11]:
 evaluate_recall(indices, sorted_indices)

(0.6, 0.32, 22.2)

In [12]:
distances, sorted_indices, distance_table, X = ivfpq.search(train_data[1], k)

In [18]:
distances

[array([3.019186 , 3.0505903, 3.0509636, 3.0580797, 3.059043 , 3.0628202,
        3.07549  , 3.0767825, 3.0770798, 3.0851982], dtype=float32)]

In [14]:
sorted_indices

[array([14771, 11621,  4643,  1690, 10482, 19035, 10061,   312, 19362,
        10929])]

In [20]:
X[10,:]

array([108,  77,  18,  23, 171, 215,  71,  11], dtype=uint8)

In [17]:
sum(np.sort(distance_table.flatten())[:8])

2.433116316795349